FROM ubuntu:latest

# Install Certbot
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:certbot/certbot
RUN apt update
RUN apt install -y python-certbot-nginx

# Install Nginx
RUN apt install -y nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Create cert
# RUN certbot certonly --verbose --noninteractive --quiet --agree-tos --nginx --email="krister.viirsaar@gmail.com" -d api.heliumlabs.org
# `certbot --nginx` has to be run manually. Above code doesn't work.

# Run nginx
CMD nginx -g 'daemon off;'
