# could use node:8, but it's libboost is too old for helium-cli
FROM ubuntu:latest

# Prepare system
RUN apt update
RUN apt install -y curl
RUN apt install -y libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt install -y nodejs

# Helium-cli conf
COPY deploy/helium-client.conf /root/.heliumcore/helium.conf

# Node app
WORKDIR /opt/app
COPY ./package.json .
RUN npm install
COPY . .
EXPOSE 3000
CMD npm run production
